name : Terraform CICD

on:
    push:
      branches:
        - master
    workflow_dispatch:  

jobs:
  Terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}      
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init 

      - name: Validate Terraform configurations
        run: terraform validate

      - name: Planned terraform changes
        run: terraform plan -out=tfplan 

