name: Re-usable workflow for planning

on:
  push:
    branches:
      - main

jobs:
  Terraform_plan:
    uses: mahadikbs/reusable-workflows/.github/workflows/terraform-plan.yaml@main
    with:
      environment: production
    secrets: 
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}  
      aws_secret_acess_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}