name: Re-usable workflow for planning

on:
  push:
    branches:
      - main

jobs:
  Terraform_plan:
    uses: mahadikbs/reusable-workflows/.github/workflows/terraform-plan.yaml@main
    with:
      environment: production
    secrets: inherit